Amélioration du README
ClubCedille/linux-cheminot pull request #5
Opened 2019-01-03 18:52 UTC by notarock

J'ai trouvé quelques points qui pourraient être améliorés dans le README. Vous en pensez quoi?

2019-01-03 19:37 UTC, notarock commented
Je vien de remarqué que le lien vers le site web de l'ETS est brisé. Je fix ça

2019-01-04 02:16 UTC, waldo121 requested changes
C'est beau, il y a seulement deux petits mots à regarder côté langue.

2019-01-04 02:16 UTC, waldo121 commented on README.md
> +_La commande `make` peut nécessité les droits de super-utilisateur puisqu'elle fait utilisation de docker._
nécessité à changer pour nécessiter

2019-01-04 02:16 UTC, waldo121 commented on README.md
> +Installer les dépendances et ensuite, cloner le répositoire.
Je m'accroche un peu en lisant répositoire. Le problème c'est que si c'est changé pour quelque chose acceptable en français (entrepôt, dépôt, référentiel,etc.), ça peut devenir moins clair.

2019-01-04 05:14 UTC, AXDOOMER commented on README.md
> +Installer les dépendances et ensuite, cloner le répositoire.
C'est un "dépôt" en frança.

2019-01-05 07:39 UTC, notarock commented on README.md
> +Installer les dépendances et ensuite, cloner le répositoire.
Que pensez-vous de "répo"? C'est en Français abrégé.

2019-01-05 07:39 UTC, notarock commented on README.md
> +_La commande `make` peut nécessité les droits de super-utilisateur puisqu'elle fait utilisation de docker._
Merci!

2019-01-05 17:28 UTC, waldo121 commented on README.md
> +Installer les dépendances et ensuite, cloner le répositoire.
<<Répositoire>>, ce n'est pas un mot en français, donc <<répo>> ce serait plus de l'anglais abrégé.

2019-01-05 20:35 UTC, AXDOOMER commented on README.md
> +Installer les dépendances et ensuite, cloner le répositoire.
"dépôt" c'est le seul bon mot en français.

2019-01-06 23:24 UTC, notarock commented
Le force push est un rebase ;)
J'ai appliqué les changemens demandés.

2019-01-08 01:10 UTC, waldo121 approved these changes

2019-01-08 01:33 UTC, merged